### ISSUE TITLE
Docker error when starting on Windows 11 WSL2 

### ISSUE THREAD

**Issue by Ditscheridou** [lucas-gaitzsch/pdf-turtle#10]
We tried to start the container on Windows 11 with WSL2 and the container failed with the following error: 

2024-04-25 16:42:34 goroutine 1 [running]:
2024-04-25 16:42:34 github.com/gofiber/fiber/v2/middleware/cors.New({0xc0000bdc20?, 0x1?, 0x2?})
2024-04-25 16:42:34     /go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.4/middleware/cors/cors.go:113 +0x8a8
2024-04-25 16:42:34 github.com/lucas-gaitzsch/pdf-turtle/server.(*Server).Serve(0xc00019c608, {0xf080a8, 0xc0002bfa40})
2024-04-25 16:42:34     /build/server/server.go:52 +0x1af
2024-04-25 16:42:34 main.main()
2024-04-25 16:42:34     /build/main.go:62 +0xca
2024-04-25 16:43:34 panic: [CORS] Insecure setup, 'AllowCredentials' is set to true, and 'AllowOrigins' is set to a wildcard.

The docker run command was the default one from the website

**Comment by lucas-gaitzsch** [comment]
Hi,
could you pull and try it again? I provide a fix for this issue.

**Comment by lucas-gaitzsch** [comment]
Is the problem resolved with the latest build?

**Comment by Ditscheridou** [comment]
We will check this next week, I currently don't have a windows machine.

**Comment by lucas-gaitzsch** [comment]
If you observe this issue again with the latest version, please repoen this issue.
